name: Caller Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/dependent-workflow.yml
    with:
      message: "Hello from the caller workflow!"
