name: Dependent Workflow

on:
  workflow_run:
    workflows: ["Caller Workflow"]
    types:
      - completed

jobs:
  dependent-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print message from dependent workflow
        run: echo "This runs only after the Caller Workflow completes."
