name: Reusable Print Message

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hi this is message is printed from workflow 1"
